config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('project.management.urls'))
]

project/management/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

# Autentication view routing
auth_urls = [
    path('login', auth_views.LoginView.as_view(template_name='auth/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('change-password/', auth_views.PasswordChangeView.as_view(template_name='auth/password_change.html'), name='password_change'),
    path('change-password-done/', auth_views.PasswordChangeDoneView.as_view(template_name='auth/password_change_done.html'), name='password_change_done'), 
]

# Account view routing
account_urls = [
    path('', views.account_list, name='account_list'),
    path('new', views.account_add, name='account_add'),
    path('<int:pk>/edit', views.account_edit, name='account_edit'),
    path('profile', views.account_profile, name='account_profile'),
]

# Student view routing
student_urls = [
    path('', views.student_list, name='student_list'),
    path('new', views.student_add, name='student_add'),
    path('<int:pk>/edit', views.student_edit, name='student_edit'),
    path('<int:pk>/detail', views.student_detail, name='student_detail'),
    path('<int:pk>/medical-record/new/', views.medical_for_student, name='medical_for_student'),
]

# Staff Member view routing
staff_member_urls = [
    path('', views.staff_member_list, name='staff_member_list'),
    path('new', views.staff_member_add, name='staff_member_add'),
    path('<int:pk>/edit', views.staff_member_edit, name='staff_member_edit'),
    path('<int:pk>/detail', views.staff_member_detail, name='staff_member_detail'),
    path('<int:pk>/medical-record/new/', views.medical_for_staff_member, name='medical_for_staff_member'),
]

# Record view routing
record_urls = [
    path('medical', views.medical_record_list, name='medical_record_list'),
    path('medical/new', views.medical_record_add, name='medical_record_add'),
    path('medical/<int:pk>/edit', views.medical_record_edit, name='medical_record_edit'),
    path('condition', views.condition_list, name='condition_list'),
    path('condition/new', views.condition_add, name='condition_add'),
    path('condition/<int:pk>/edit/', views.condition_edit, name='condition_edit'),
    path('section', views.section_list, name='section_list'),
    path('section/new', views.section_add, name='section_add'),
    path('section/<int:pk>/edit/', views.section_edit, name='section_edit'),
    path('grade-level', views.grade_level_list, name='grade_level_list'),
    path('grade-level/new', views.grade_level_add, name='grade_level_add'),
    path('grade-level/<int:pk>/edit/', views.grade_level_edit, name='grade_level_edit'),
]

# Import export views
data_urls = [
    path('export-students/<str:type>/', views.export_students, name='export_students'),
    path('export-staff-members/<str:type>/', views.export_staff_members, name='export_staff_members'),
    path('export-medical/<int:pk>/<str:type>/', views.export_medical_student, name='export_medical_student'),
    path('export-medical/<int:pk>/<str:type>/', views.export_medical_staff_member, name='export_medical_staff_member'),
    path('export-medical<str:type>/', views.export_medical, name='export_medical'),
    path('export-condition/<str:type>/', views.export_conditions, name='export_conditions'),
    path('export-grade_level<str:type>/', views.export_grade_level, name='export_grade_level'),
    path('export-section<str:type>/', views.export_section, name='export_section'),
]

# Main URL routing patterns
urlpatterns = [
    path('', views.home, name='home'),
    path('auth/', include(auth_urls)),
    path('accounts/', include(account_urls)),
    path('students/', include(student_urls)),
    path('staff-members/', include(staff_member_urls)),
    path('records/', include(record_urls)),
    path('data/', include(data_urls))
]

project/management/models.py
from django.contrib.auth.models import User
# from django.dispatch import receiver
# from django.db.models.signals import post_save
from django.db import models
from datetime import date
import datetime

GENDER_CHOICES = (
    ('m', 'Male'),
    ('f', 'Female'),
)

PATIENT_CHOICES = (
    ('s', 'Student'),
    ('sm', 'Staff Member'),
)

CSTATUS_CHOICES = (
    ('s', 'Single'),
    ('m', 'Married'),
    ('w', 'Widowed'),
    ('d', 'Divorced'),
    ('l', 'Legally Separated'),
)

BMICATEGORY_CHOICES = (
    ('vsu', 'Very severely underweight'),
    ('su', 'Severely underweight'),
    ('u', 'Underweight'),
    ('n', 'Normal'),
    ('o', 'Overweight'),
    ('mo', 'Moderately obese'),
    ('so', 'Severely obese'),
    ('vso', 'Very severely obese'),	
)

class GradeLevel(models.Model):
    grade_level = models.CharField(max_length=50)

    class Meta:
        ordering = ('pk',)

    def __str__(self):
        return self.grade_level

class Section(models.Model):
    grade_level = models.ForeignKey(GradeLevel, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=254)

    class Meta:
        ordering = ('pk',)

    def __str__(self):
        return '{} {}'.format(self.grade_level, self.name)

class Patient(models.Model):
    section = models.ForeignKey(Section, on_delete=models.SET_NULL, null=True)
    patient_type = models.CharField(max_length=11, choices=PATIENT_CHOICES, default='s')
    first_name = models.CharField(max_length=50, null=True)
    middle_name = models.CharField(max_length=50, blank=True)
    last_name = models.CharField(max_length=50, null=True)
    gender = models.CharField(max_length=11, choices=GENDER_CHOICES, default='m')
    civil_status = models.CharField(max_length=11, choices=CSTATUS_CHOICES, default='s')
    date_of_birth = models.DateField(null=True)
    age = models.PositiveIntegerField(default=0, null=True)
    full_address = models.CharField(max_length=100, blank=True)
    is_active = models.BooleanField(default=True)
    profile_photo = models.FileField(blank=True, null=True)

    class Meta:
        ordering = ('pk',)
            
    @property
    def image_url(self):
        if self.profile_photo and hasattr(self.profile_photo, 'url'):
            return self.profile_photo.url

    def __str__(self):
        return '{} {} {}'.format(self.first_name, self.middle_name, self.last_name)

    def get_age(self):
        today = date.today()
        try:
            birthday = self.date_of_birth.replace(year=today.year)
        except ValueError: # raised when birth date is Feb 29 and the current year is not a leap year
            birthday = self.date_of_birth.replace(year=today.year, month=birthday.month+1, day=1)
        if birthday > today:
            return today.year - self.date_of_birth.year - 1
        else:
            return today.year - self.date_of_birth.year

    def get_full_address(self):
        return '{}'.format(self.street_address)

    def get_full_name(self):
        return '{} {} {}'.format(self.first_name, self.middle_name, self.last_name)

    def get_section(self):
        return '{}'.format(self.section)

    def save(self):
        self.age = self.get_age()
        super(Patient, self).save()

class Condition(models.Model):
    name = models.CharField(max_length=254, unique=True)
    description = models.TextField(max_length=4000, blank=True)

    class Meta:
        ordering = ('pk',)

    def __str__(self):
        return self.name

class MedicalRecord(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.SET_NULL, null=True)
    height = models.PositiveIntegerField('Height(cm)', default=0, help_text='Height in cm')
    weight = models.PositiveIntegerField('Weight(kg)', default=0, help_text="Weight in kg")
    bmi = models.FloatField(blank=True)
    bmi_category = models.CharField(max_length=50, choices=BMICATEGORY_CHOICES, blank=True)
    summarized_medical_record = models.TextField(max_length=4000)
    condition = models.ForeignKey(Condition, on_delete=models.SET_NULL, null=True, blank=True)
    medicine_used = models.CharField(max_length=100, unique=False, blank=True)
    reason_of_admission = models.CharField(max_length=100, unique=False)
    checkup_date = models.DateTimeField()

    class Meta:
        ordering = ('-checkup_date',)

    def __str__(self):
        return 'Medical Record No.{} of {}'.format(self.pk, self.Patient)
		
    def get_bmi(self):
        height_in_meters = self.height*0.01
        bmi = self.weight/(height_in_meters*height_in_meters)
        return str(bmi)[:5]

    def get_bmi_category(self):
        height_in_meters = float(self.height*0.01)
        bmi = self.weight/(height_in_meters*height_in_meters)
        if(bmi < 15):
            bmi_category = "vsu"
        elif(bmi > 15 and bmi < 16) :
            bmi_category = "su"
        elif(bmi > 16 and bmi < 18.5) :
            bmi_category = "u"
        elif(bmi > 18.5 and bmi < 25 ):
            bmi_category = "n"
        elif(bmi > 25 and bmi < 30):
            bmi_category = "o"
        elif(bmi > 30 and bmi < 35):
            bmi_category = "mo"
        elif(bmi > 35 and bmi < 40):
            bmi_category = "so"
        elif(bmi > 40):
            bmi_category = "vso"
        return bmi_category
		
    def save(self):
        self.bmi = self.get_bmi()
        self.bmi_category = self.get_bmi_category()
        super(MedicalRecord, self).save()

project/templates/management/records/students/detail.html
{% extends 'management/base.html' %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'vendors/css/dataTables.bootstrap4.min.css' %}">
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="{% url 'student_list' %}">Students</a></li>
  <li class="breadcrumb-item active">{{ student.get_full_name }}</li>
</ol>
{% endblock %}

{% block content %}

<div class="card">
  <div class="card-header">
    {{student.get_full_name}}'s Record
    <a href="{% url 'student_list' %}" class="btn btn-sm btn-danger float-right mt-1"><i class="fa fa-close"></i> </a>
  </div>
  <div class="card-body">
    <div class="row">

      <div class="col-sm-4">
        <div class="card">
          <div class="card-header">
            <img
              src="{% if student.profile_photo %}{{ student.profile_photo.url }}{% else %}{% static 'img/avatars/avatar.svg' %}{% endif %}"
              class="img-fluid img-thumbnail" alt="student.get_full_name">
          </div>
          <div class="card-body">
            <h4 style="margin-bottom:-4">BIO</h4>
            <hr>
            <strong>Student Record No:</strong> {{ student.pk }} <br>
            <strong>Section:</strong> {{ student.section }} <br>
            <strong>First Name:</strong> {{ student.first_name }} <br>
            <strong>Middle Name:</strong> {{ student.middle_name }} <br>
            <strong>Last Name:</strong> {{ student.last_name }} <br>
            <strong>Address:</strong> {{ student.full_address }} <br>
            <strong>Birthday:</strong> {{ student.date_of_birth }} <br>
            <strong>Gender:</strong> {{ student.get_gender_display }} <br>
            <strong>Civil Status:</strong> {{ student.get_civil_status_display }} <br>
            <strong>Age:</strong> {{ student.get_age }} year/s old<br>

            <h4 class="mt-5" style="margin-bottom:-4">Latest Vitals</h4>
            <hr>
            {% if latest_med_rec %}
            <strong>Weight:</strong> {{ latest_med_rec.weight }} kg<br>
            <strong>Height:</strong> {{ latest_med_rec.height }} cm<br>
            <strong>BMI:</strong> {{ latest_med_rec.bmi }}<br>
            <strong>BMI Category:</strong> {{ latest_med_rec.get_bmi_category_display }}
            {% else %}
            No medical record found for this student.
            {% endif %}
          </div>
          {% if user.is_staff %}
          <div class="card-footer">
            <a href="{% url 'student_edit' student.pk %}" class="btn btn-sm btn-primary"><i class="fa fa-pencil"></i>
              Edit</a>
          </div>
          {% endif %}
        </div>
      </div>

      <div class="col-sm-8">

        <!-- Medical Records -->
        <div class="card">
          <div class="card-header">
            {{student.get_full_name}}'s Medical Records
            {% if user.is_staff %}
            <a href="{% url 'medical_for_student' student.pk %}" class="btn btn-sm btn-success float-right mt-1"><i
                class="fa fa-plus"></i> New</a>
            <button type="button" title="Export {{ student.get_full_name }}'s Medical Data"
              class="btn btn-sm btn-info float-right mt-1 mr-3" data-toggle="modal" data-target="#export-med"><i
                class="fa fa-download"></i></a>
              <button type="button" title="Import {{ student.get_full_name }}'s Medical Data"
                class="btn btn-sm btn-info float-right mt-1" data-toggle="modal" data-target="#import-med"><i
                  class="fa fa-upload"></i></a>
            {% endif %}
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table id="medical" class="table table-striped table-bordered" style="width:100%">
                <thead>
                  <tr>
                    <th>Medical Record No.</th>
                    <th>Height and Weight</th>
                    <th>BMI</th>
                    <th>BMI Category</th>
                    <th>Date of Consultation</th>
                    <th>Medicine used</th>
                    <th>Purpose of Consultation</th>
                  </tr>
                </thead>
                <tbody>
                  {% if medical_records %}
                  {% for medical_record in medical_records %}
                  <tr>
                    <td><a style="text-decoration:none" href="{% url 'medical_record_edit' medical_record.pk %}">Record No. {{ medical_record.pk }}</a></td>
                    <td>{{ medical_record.height }} cm, {{ medical_record.weight }} kg</td>
                    <td>{{ medical_record.bmi }}</td>
                    <td>{{ medical_record.get_bmi_category_display }}</td>
                    <td>{{ medical_record.checkup_date }}</td>
                    <td>{{ medical_record.medicine_used }}</td>
                    <td>{{ medical_record.reason_of_admission }}</td>
                  </tr>
                  {% endfor %}
                  {% endif %}
                </tbody>
              </table>
            </div>
          </div>
        </div>
        <!-- / Medical Records -->

      </div>

    </div>
  </div>
</div>

{% endblock %}

{% block modals %}
<div id="export-med" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="Export student's Medical Data"
  aria-hidden="true">
  <div class="modal-dialog modal-primary" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Export {{ student.get_full_name }}'s Medical Data</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body text-center">
        <p style="margin-bottom:20px">Choose the format you wish to export the data:</p>
        <div class="btn-group-vertical" role="group" aria-label="Select export filetype">
          <a href="{% url 'export_medical_student' student.pk 'csv' %}" class="btn btn-lg btn-primary">
            <i class="fa fa-download"></i> Export as .csv
          </a>
          <a href="{% url 'export_medical_student' student.pk 'xls' %}" class="btn btn-lg btn-primary">
            <i class="fa fa-download"></i> Export as .xls
          </a>
          <a href="{% url 'export_medical_student' student.pk 'json' %}" class="btn btn-lg btn-primary">
            <i class="fa fa-download"></i> Export as .json
          </a>
        </div>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div id="import-med" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="Import student Medical Data"
  aria-hidden="true">
  <div class="modal-dialog modal-primary" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Import {{ student.get_full_name }}'s Medical Data</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">
        <p class="alert alert-warning">
          <strong>Please be sure to have the correct format of data in your file.<br>
            If file fails to upload or does not show the changes you made after the upload please make sure the format
            of the fields are correct.
          </strong>
        </p>
        <p class="file-input field">
          <form class="md-form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-sm-12 alert alert-info">
              <label for="file-input">Select the file to upload:</label><br>
              <input class="form-control" id="fileInput" type="file" name="medical">
            </div>
            <button id="upload-btn" onclick="upload(event)" class="btn btn-lg btn-success" type="submit">
              <i class="fa fa-upload"></i> Upload
            </button>
          </form>
        </p>
      </div>
    </div>
    <!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
{% endblock %}

{% block scripts %}
<script src="{% static 'vendors/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendors/js/dataTables.bootstrap4.min.js' %}"></script>
<script>
  function upload(event) {
    if (!document.getElementById("fileInput").value) {
      event.preventDefault();
      alert("Please select a file to upload!");
    }
  }
  $(document).ready(function () {
    $('#medical,#pregnancy,#dental').DataTable();
  });
</script>
{% endblock %}

project/templates/management/records/students/list.html
{% extends 'management/base.html' %}

{% load static %}

{% block styles %}
<link rel="stylesheet" href="{% static 'vendors/css/dataTables.bootstrap4.min.css' %}">
{% endblock %}

{% block breadcrumb %}
<ol class="breadcrumb">
  <li class="breadcrumb-item active">Students</li>
</ol>
{% endblock %}

{% block content %}
<div class="card">
  <div class="card-header">
    {% if user.is_staff %}<a href="{% url 'student_add' %}" class="btn btn-md btn-success float-left mt-1"><i class="fa fa-plus"></i> New</a>{% endif %}
    <a href="{% url 'home' %}" class="btn btn-md btn-danger float-right mt-1"><i class="fa fa-close"></i></a>
	{% if user.is_staff %}
    <button type="button" title="Export Students' Data" class="btn btn-md btn-info float-right mt-1 mr-3" data-toggle="modal" data-target="#export-modal"><i class="fa fa-download"></i></a>
    <button type="button" title="Import Students' Data" class="btn btn-md btn-info float-right mt-1" data-toggle="modal" data-target="#import-modal"><i class="fa fa-upload"></i></a>
	{% endif %}
  </div>
  <div class="card-body">
    <div class="table-responsive">
		<table id="students" class="table table-striped table-bordered" style="width:100%">
		  <thead>
			<tr>
			  <th>Name</th>
			  <th>Gender</th>
			  <th>Date of Birth</th>
			  <th>Age(Present)</th>
			  <th>Section</th>
			  <th>Is Active?</th>
			</tr>
		  </thead>
		  <tbody>
			{% if students %}
			  {% for student in students %}
			  {% if not student.user.is_staff %}
			  <tr>
				<td><a style="text-decoration:none" href="{% url 'student_detail' student.pk %}">{{ student.get_full_name }}</a></td>
				<td>{{ student.get_gender_display }}</td>
				<td>{{ student.date_of_birth }}</td>
				<td>{{ student.age }}</td>
				<td>{{ student.get_section }}</td>
				<td class="bg-{% if student.is_active %}success{% else %}danger{% endif %}">{% if student.is_active %}Yes{% else %}No{% endif %}</td>
			  </tr>
			  {% endif %}
			  {% endfor %}
			{% endif %}
		  </tbody>
		</table>
	</div>
  </div>
</div>
{% endblock %}

{% block modals %}
<div id="export-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="Export student Data" aria-hidden="true">
  <div class="modal-dialog modal-primary" role="document">
    <div class="modal-content">
      <div class="modal-header">
	    <h4 class="modal-title">Export Students' Data</h4>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		  <span aria-hidden="true">×</span>
		</button>
	  </div>
	  <div class="modal-body text-center">
		<p style="margin-bottom:20px">Choose the format you wish to export the data:</p>
        <div class="btn-group-vertical" role="group" aria-label="Select export filetype">
		  <a href="{% url 'export_students' 'csv' %}" class="btn btn-lg btn-primary">
			<i class="fa fa-download"></i> Export as .csv
		  </a>
		  <a href="{% url 'export_students' 'xls' %}" class="btn btn-lg btn-primary">
			<i class="fa fa-download"></i> Export as .xls
		  </a>
		  <a href="{% url 'export_students' 'json' %}" class="btn btn-lg btn-primary">
			<i class="fa fa-download"></i> Export as .json
		  </a>
        </div>
	  </div>
	</div>
	<!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div id="import-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="Import student Data" aria-hidden="true">
  <div class="modal-dialog modal-primary" role="document">
    <div class="modal-content">
      <div class="modal-header">
	    <h4 class="modal-title">Import Students' Data</h4>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		  <span aria-hidden="true">×</span>
		</button>
	  </div>
	  <div class="modal-body">
		<p class="alert alert-warning"><strong>Please be sure to have the correct format of data in your file. <br> If file fails to upload or does not show the changes you made after the upload please make sure the format of the fields are correct, especially the dates(yyyy-mm-dd).</strong></p>
		<p class="file-input field">
		  <form class="md-form" method="post" enctype="multipart/form-data">
			{% csrf_token %}
			<div class="col-sm-12 alert alert-info">
			  <label for="file-input">Select the file to upload:</label><br>
			  <input class="form-control" id="fileInput" type="file" name="students">
			</div>
			<button id="upload-btn"  onclick="upload(event)" class="btn btn-lg btn-success" type="submit">
			  <i class="fa fa-upload"></i> Upload
			</button>
		  </form>
		</p>
	  </div>
	</div>
	<!-- /.modal-content -->
  </div>
  <!-- /.modal-dialog -->
</div>
<!-- /.modal -->
{% endblock %}

{% block scripts %}
<script src="{% static 'vendors/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'vendors/js/dataTables.bootstrap4.min.js' %}"></script>
<script>
function upload(event) {
	if (!document.getElementById("fileInput").value) {
	  event.preventDefault();
	  alert("Please select a file to upload!");
	}
}
$(document).ready(function() {
  $('#students').DataTable();
});
</script>
{% endblock %}